spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/redpig?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#生成的代码存放目录:resources下
filePlace: tmp
#vm模板存放目录
vmPlace: generator

upload: /files